# Generated by Django 3.1.7 on 2021-05-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('FirstName', models.CharField(blank=True, default='', max_length=50)),
                ('SecondName', models.CharField(blank=True, default='', max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, default='', max_length=50)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Club', models.CharField(blank=True, max_length=50, null=True)),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Rank', models.CharField(blank=True, max_length=50, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('LastGame', models.DateField(blank=True, null=True)),
                ('Confirmed', models.BooleanField(default=False)),
                ('OfficialRole', models.IntegerField(default=0)),
            ],
        ),
    ]
