# Generated by Django 3.1.7 on 2021-05-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('LocationName', models.CharField(max_length=256)),
                ('StartDate', models.CharField(blank=True, max_length=256, null=True)),
                ('EndDate', models.CharField(blank=True, max_length=256, null=True)),
                ('RulesInfo', models.CharField(blank=True, max_length=256, null=True)),
                ('ParticipationType', models.IntegerField()),
                ('ParticipationTypeName', models.CharField(default='Personal', max_length=50)),
                ('TournamentType', models.IntegerField(default=0)),
                ('IsHeadStart', models.BooleanField(default=False)),
                ('TimeControlInfo', models.CharField(blank=True, max_length=256, null=True)),
                ('IsRated', models.BooleanField(default=False)),
                ('BoardNum', models.IntegerField(blank=True, null=True)),
                ('CurrentRoundNum', models.IntegerField(default=0)),
                ('RoundNum', models.IntegerField()),
                ('State', models.IntegerField(default=0)),
                ('StateName', models.CharField(default='Registration', max_length=50)),
                ('TossType', models.IntegerField()),
                ('TossName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.IntegerField()),
                ('TournamentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RegistrationStatus', models.IntegerField(default=0)),
                ('Rating', models.IntegerField(default=0)),
                ('TournamentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament')),
                ('UserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True, null=True)),
                ('ResultType', models.IntegerField(default=4)),
                ('ResultName', models.CharField(max_length=20)),
                ('RoundNumber', models.IntegerField()),
                ('FirstPlayerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FirstPlayerId', to='tournament.tournamentplayer')),
                ('SecondPlayerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondPlayerId', to='tournament.tournamentplayer')),
                ('TournamentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament')),
            ],
        ),
    ]
